import type { Metadata } from "next";
import { Inter, Noto_Sans_JP } from "next/font/google";
import "../globals.css";

import Container from "@/app/components/Container"

const inter = Inter({ subsets: ["latin"] });
const noto = Noto_Sans_JP({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
        <body className={noto.className}>
          <Container>
            {children}
          </Container>
        </body>
    </html>
  );
}
