import type { Metadata } from "next";
import { Inter , Noto_Sans_JP } from "next/font/google";
import "../globals.css";
import SessionWrapper from "../components/SessionWrapper";
import Header from "../components/Header";

import Container from "@/app/components/Container"
import HeaderNashi from "../components/HeaderNashi";

const inter = Inter({ subsets: ["latin"] });
const noto = Noto_Sans_JP({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="ja">
        <body className={noto.className}>
          <Container>
            {/* <Header /> */}
            <HeaderNashi />
            {children}
          </Container>
        </body>
      </html>
    </SessionWrapper>
  );
}
